// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwhgpoizfzdhnzsyuvas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aGdwb2l6ZnpkaG56c3l1dmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzEzMTksImV4cCI6MjA3MDMwNzMxOX0.J4QT-NR-Qy2ijjvOQHzh1KAWqlG7_n1LyXujdo-62aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});